// client/src/pages/NotFound.vue

<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900">
    <div class="text-center">
      <h1 class="text-9xl font-bold text-gray-300 dark:text-gray-700">404</h1>
      <h2 class="text-4xl font-bold text-gray-900 dark:text-white mb-4">Page Not Found</h2>
      <p class="text-lg text-gray-600 dark:text-gray-300 mb-8">
        The page you're looking for doesn't exist.
      </p>
      <router-link 
        to="/"
        class="inline-flex items-center px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
      >
        <i class="bx bx-home mr-2"></i>
        Go Home
      </router-link>
    </div>
  </div>
</template>

<script>
export default {
  name: 'NotFound'
}
</script>

// client/src/pages/not-found.tsx
import React from 'react';
import { Link } from 'wouter';

export default function NotFound() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100">
      <div className="text-9xl font-bold text-blue-600 dark:text-blue-500 mb-6">404</div>
      <h1 className="text-4xl md:text-5xl font-bold text-center mb-4">Page Not Found</h1>
      <p className="text-xl text-center text-gray-600 dark:text-gray-400 max-w-md mb-8">
        The page you are looking for doesn't exist or has been moved.
      </p>
      <Link href="/">
        <a className="px-6 py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors">
          Go Back Home
        </a>
      </Link>
    </div>
  );
}
