// client/src/components/ScrollProgress.vue

<template>
  <div 
    class="fixed top-0 left-0 w-full h-1 bg-gray-200 dark:bg-gray-700 z-50"
  >
    <div 
      class="h-full bg-blue-600 transition-all duration-150 ease-out"
      :style="{ width: scrollProgress + '%' }"
    ></div>
  </div>
</template>

<script>
export default {
  name: 'ScrollProgress',
  data() {
    return {
      scrollProgress: 0
    }
  },
  mounted() {
    window.addEventListener('scroll', this.updateScrollProgress)
  },
  beforeUnmount() {
    window.removeEventListener('scroll', this.updateScrollProgress)
  },
  methods: {
    updateScrollProgress() {
      const scrollTop = window.pageYOffset
      const docHeight = document.documentElement.scrollHeight - window.innerHeight
      const scrollPercent = (scrollTop / docHeight) * 100
      this.scrollProgress = Math.min(scrollPercent, 100)
    }
  }
}
</script>

// client/src/components/ScrollProgress.tsx
import React, { useState, useEffect } from 'react';

export default function ScrollProgress() {
  const [scrollProgress, setScrollProgress] = useState(0);
  
  useEffect(() => {
    const handleScroll = () => {
      // Calculate scroll progress as a percentage
      const totalHeight = document.documentElement.scrollHeight - window.innerHeight;
      const scrollPosition = window.scrollY;
      const progress = (scrollPosition / totalHeight) * 100;
      
      setScrollProgress(progress);
    };
    
    // Add scroll event listener
    window.addEventListener('scroll', handleScroll);
    
    // Clean up event listener on component unmount
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);
  
  return (
    <div className="fixed top-0 left-0 right-0 h-1 z-50">
      <div 
        className="h-full bg-gradient-to-r from-purple-400 to-purple-600"
        style={{ width: `${scrollProgress}%` }}
      />
    </div>
  );
}
